//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Keylime Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	out.EKCertificateStore = in.EKCertificateStore
	out.SecurePayload = in.SecurePayload
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.Registrar != nil {
		in, out := &in.Registrar, &out.Registrar
		*out = new(RegistrarStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.EKCertificate != nil {
		in, out := &in.EKCertificate, &out.EKCertificate
		*out = new(EKCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.Verifier != nil {
		in, out := &in.Verifier, &out.Verifier
		*out = new(VerifierStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployment) DeepCopyInto(out *Deployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployment.
func (in *Deployment) DeepCopy() *Deployment {
	if in == nil {
		return nil
	}
	out := new(Deployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Deployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentList) DeepCopyInto(out *DeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Deployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentList.
func (in *DeploymentList) DeepCopy() *DeploymentList {
	if in == nil {
		return nil
	}
	out := new(DeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	out.InitGlobal = in.InitGlobal
	out.NodeInfo = in.NodeInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKCertificate) DeepCopyInto(out *EKCertificate) {
	*out = *in
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(TPM)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorityChains != nil {
		in, out := &in.AuthorityChains, &out.AuthorityChains
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKCertificate.
func (in *EKCertificate) DeepCopy() *EKCertificate {
	if in == nil {
		return nil
	}
	out := new(EKCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKCertificateStore) DeepCopyInto(out *EKCertificateStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKCertificateStore.
func (in *EKCertificateStore) DeepCopy() *EKCertificateStore {
	if in == nil {
		return nil
	}
	out := new(EKCertificateStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageInfo) DeepCopyInto(out *ImageInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageInfo.
func (in *ImageInfo) DeepCopy() *ImageInfo {
	if in == nil {
		return nil
	}
	out := new(ImageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitGlobal) DeepCopyInto(out *InitGlobal) {
	*out = *in
	out.InitialImage = in.InitialImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitGlobal.
func (in *InitGlobal) DeepCopy() *InitGlobal {
	if in == nil {
		return nil
	}
	out := new(InitGlobal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
	out.TenantImageInfo = in.TenantImageInfo
	out.RegistrarImageInfo = in.RegistrarImageInfo
	out.VerifierImageInfo = in.VerifierImageInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrarStatus) DeepCopyInto(out *RegistrarStatus) {
	*out = *in
	if in.AIK != nil {
		in, out := &in.AIK, &out.AIK
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.EK != nil {
		in, out := &in.EK, &out.EK
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.EKCert != nil {
		in, out := &in.EKCert, &out.EKCert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.AgentCert != nil {
		in, out := &in.AgentCert, &out.AgentCert
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrarStatus.
func (in *RegistrarStatus) DeepCopy() *RegistrarStatus {
	if in == nil {
		return nil
	}
	out := new(RegistrarStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurePayload) DeepCopyInto(out *SecurePayload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurePayload.
func (in *SecurePayload) DeepCopy() *SecurePayload {
	if in == nil {
		return nil
	}
	out := new(SecurePayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPM) DeepCopyInto(out *TPM) {
	*out = *in
	if in.Specification != nil {
		in, out := &in.Specification, &out.Specification
		*out = new(TPMSpecification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPM.
func (in *TPM) DeepCopy() *TPM {
	if in == nil {
		return nil
	}
	out := new(TPM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TPMEncryptionAlgs) DeepCopyInto(out *TPMEncryptionAlgs) {
	{
		in := &in
		*out = make(TPMEncryptionAlgs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMEncryptionAlgs.
func (in TPMEncryptionAlgs) DeepCopy() TPMEncryptionAlgs {
	if in == nil {
		return nil
	}
	out := new(TPMEncryptionAlgs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TPMHashAlgs) DeepCopyInto(out *TPMHashAlgs) {
	{
		in := &in
		*out = make(TPMHashAlgs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMHashAlgs.
func (in TPMHashAlgs) DeepCopy() TPMHashAlgs {
	if in == nil {
		return nil
	}
	out := new(TPMHashAlgs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPMPolicy) DeepCopyInto(out *TPMPolicy) {
	*out = *in
	if in.PCR0 != nil {
		in, out := &in.PCR0, &out.PCR0
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR1 != nil {
		in, out := &in.PCR1, &out.PCR1
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR2 != nil {
		in, out := &in.PCR2, &out.PCR2
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR3 != nil {
		in, out := &in.PCR3, &out.PCR3
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR4 != nil {
		in, out := &in.PCR4, &out.PCR4
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR5 != nil {
		in, out := &in.PCR5, &out.PCR5
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR6 != nil {
		in, out := &in.PCR6, &out.PCR6
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR7 != nil {
		in, out := &in.PCR7, &out.PCR7
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR8 != nil {
		in, out := &in.PCR8, &out.PCR8
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR9 != nil {
		in, out := &in.PCR9, &out.PCR9
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR10 != nil {
		in, out := &in.PCR10, &out.PCR10
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR11 != nil {
		in, out := &in.PCR11, &out.PCR11
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR12 != nil {
		in, out := &in.PCR12, &out.PCR12
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR13 != nil {
		in, out := &in.PCR13, &out.PCR13
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR14 != nil {
		in, out := &in.PCR14, &out.PCR14
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR15 != nil {
		in, out := &in.PCR15, &out.PCR15
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR16 != nil {
		in, out := &in.PCR16, &out.PCR16
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR17 != nil {
		in, out := &in.PCR17, &out.PCR17
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR18 != nil {
		in, out := &in.PCR18, &out.PCR18
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR19 != nil {
		in, out := &in.PCR19, &out.PCR19
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR20 != nil {
		in, out := &in.PCR20, &out.PCR20
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR21 != nil {
		in, out := &in.PCR21, &out.PCR21
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR22 != nil {
		in, out := &in.PCR22, &out.PCR22
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCR23 != nil {
		in, out := &in.PCR23, &out.PCR23
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMPolicy.
func (in *TPMPolicy) DeepCopy() *TPMPolicy {
	if in == nil {
		return nil
	}
	out := new(TPMPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TPMSigningAlgs) DeepCopyInto(out *TPMSigningAlgs) {
	{
		in := &in
		*out = make(TPMSigningAlgs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMSigningAlgs.
func (in TPMSigningAlgs) DeepCopy() TPMSigningAlgs {
	if in == nil {
		return nil
	}
	out := new(TPMSigningAlgs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPMSpecification) DeepCopyInto(out *TPMSpecification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMSpecification.
func (in *TPMSpecification) DeepCopy() *TPMSpecification {
	if in == nil {
		return nil
	}
	out := new(TPMSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifierStatus) DeepCopyInto(out *VerifierStatus) {
	*out = *in
	if in.V != nil {
		in, out := &in.V, &out.V
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.TPMPolicy != nil {
		in, out := &in.TPMPolicy, &out.TPMPolicy
		*out = new(TPMPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.VTPMPolicy != nil {
		in, out := &in.VTPMPolicy, &out.VTPMPolicy
		*out = new(TPMPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AcceptTPMHashAlgs != nil {
		in, out := &in.AcceptTPMHashAlgs, &out.AcceptTPMHashAlgs
		*out = make([]TPMHashAlg, len(*in))
		copy(*out, *in)
	}
	if in.AcceptTPMEncryptionAlgs != nil {
		in, out := &in.AcceptTPMEncryptionAlgs, &out.AcceptTPMEncryptionAlgs
		*out = make([]TPMEncryptionAlg, len(*in))
		copy(*out, *in)
	}
	if in.AcceptTPMSigningAlgs != nil {
		in, out := &in.AcceptTPMSigningAlgs, &out.AcceptTPMSigningAlgs
		*out = make([]TPMSigningAlg, len(*in))
		copy(*out, *in)
	}
	in.LastReceivedQuote.DeepCopyInto(&out.LastReceivedQuote)
	in.LastSuccessfulAttestation.DeepCopyInto(&out.LastSuccessfulAttestation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifierStatus.
func (in *VerifierStatus) DeepCopy() *VerifierStatus {
	if in == nil {
		return nil
	}
	out := new(VerifierStatus)
	in.DeepCopyInto(out)
	return out
}
