#!/usr/bin/env bash
if [ $0 != "-bash" ] ; then
    pushd `dirname "$0"` > /dev/null 2>&1 
fi
KEYLIME_SERVICE_DIR=$(pwd)
if [ $0 != "-bash" ] ; then
    popd > /dev/null 2>&1
fi

source $KEYLIME_SERVICE_DIR/../util/common.sh

KEYLIME_TENANT_POD=$(kubectl get pods --namespace ${KEYLIME_NAMESPACE} | grep tenant | awk '{ print $1 }')

KEYLIME_TENANT_RECEIVED_COMMAND="$*"

if [[ -z $1 ]]
then
    KEYLIME_TENANT_COMMAND="bash"
fi

echo "$KEYLIME_TENANT_RECEIVED_COMMAND" | grep -q "\-c"
if [[ $? -eq 0 ]]
then
    KEYLIME_TENANT_COMMAND="bash -c \"/usr/local/bin/kt $KEYLIME_TENANT_RECEIVED_COMMAND\""
fi

announce "Executing command \"$KEYLIME_TENANT_COMMAND\" on pod \"$KEYLIME_TENANT_POD\"..."
KEYLIME_TENANT_COMMAND="kubectl exec -it $KEYLIME_TENANT_POD --namespace ${KEYLIME_NAMESPACE} -- $KEYLIME_TENANT_COMMAND"
eval $KEYLIME_TENANT_COMMAND
