#!/usr/bin/env bash
if [ $0 != "-bash" ] ; then
    pushd `dirname "$0"` > /dev/null 2>&1 
fi
KEYLIME_SERVICE_DIR=$(pwd)
if [ $0 != "-bash" ] ; then
    popd > /dev/null 2>&1
fi

source $KEYLIME_SERVICE_DIR/../common.sh

cat <<EOF > ${KEYLIME_WORK_DIR}/sed-commands
s^REPLACE_KEYLIME_NAMESPACE^$KEYLIME_NAMESPACE^g
s^REPLACE_KEYLIME_IMAGE_PREFIX^$KEYLIME_IMAGE_PREFIX^g
s^REPLACE_KEYLIME_ACTUAL_CERTS_DIR^$KEYLIME_ACTUAL_CERTS_DIR^g
s^REPLACE_KEYLIME_CFGMAP_NAME^$KEYLIME_CFGMAP_NAME^g
s^REPLACE_KEYLIME_TLS_SECRETS_NAME^$KEYLIME_TLS_SECRETS_NAME^g
s^REPLACE_KEYLIME_IMAGE_PULL_POLICY^$KEYLIME_IMAGE_PULL_POLICY^g
s^REPLACE_KEYLIME_REGISTRAR_PORT_EXTERNAL^$((KEYLIME_REGISTRAR_PORT+KEYLIME_SERVICE_PORT_OFFSET))^g
s^REPLACE_KEYLIME_REGISTRAR_TLS_PORT_EXTERNAL^$((KEYLIME_REGISTRAR_TLS_PORT+KEYLIME_SERVICE_PORT_OFFSET))^g
s^REPLACE_KEYLIME_REGISTRAR_PORT^$KEYLIME_REGISTRAR_PORT^g
s^REPLACE_KEYLIME_REGISTRAR_TLS_PORT^$KEYLIME_REGISTRAR_TLS_PORT^g
s^REPLACE_KEYLIME_REGISTRAR_REPLICAS^$KEYLIME_REGISTRAR_REPLICAS^g
s^REPLACE_KEYLIME_REGISTRAR_SERVICE_NAME^$KEYLIME_REGISTRAR_SERVICE_NAME^g
s^REPLACE_KEYLIME_REGISTRAR_SERVICE_TYPE^$KEYLIME_REGISTRAR_SERVICE_TYPE^g
EOF

if [[ $KEYLIME_REGISTRAR_POD_DEBUG -eq 1 ]]
then
    echo "s^#REPLACE_KEYLIME_REGISTRAR_POD_DEBUG^^g" >> ${KEYLIME_WORK_DIR}/sed-commands
fi

cat $KEYLIME_SERVICE_DIR/../../templates/registrar.yaml.in | sed -f ${KEYLIME_WORK_DIR}/sed-commands > ${KEYLIME_WORK_DIR}/registrar.yaml

generate_service_entry ${KEYLIME_REGISTRAR_SERVICE_NAME}-http registrar $KEYLIME_REGISTRAR_SERVICE_TYPE $KEYLIME_REGISTRAR_PORT $((KEYLIME_REGISTRAR_PORT+KEYLIME_SERVICE_PORT_OFFSET))
generate_service_entry ${KEYLIME_REGISTRAR_SERVICE_NAME} registrar $KEYLIME_REGISTRAR_SERVICE_TYPE $KEYLIME_REGISTRAR_TLS_PORT $((KEYLIME_REGISTRAR_TLS_PORT+KEYLIME_SERVICE_PORT_OFFSET))

echo " "
cat ${KEYLIME_WORK_DIR}/registrar.yaml
echo " "

kubectl apply -f ${KEYLIME_WORK_DIR}/registrar.yaml

if [[ ! -z ${KEYLIME_WORK_DIR} ]]
then
    rm -rf ${KEYLIME_WORK_DIR}
fi
